export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Javascript"
  | "HTML"
  | "CSS"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Socket.io"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Shadcn UI"
  | "PHP"
  | "REST API"
  | "Prisma"
  | "JAVA"
  | "C++"
  | "Python"
  | "Supabase"
  | "PostgreSQL"
  | "Expo"
  | "Shopify"
  | "Go"
  | "Redis"
  | "Docker"
  | "Rust"
  | "Tauri"
  | "Electron"
  | "SQLite"
  | "Laravel"
  | "Vercel AI SDK"
  | "C#"
  | ".NET"
  | "ASP.NET"
  | "GSAP"
  | "Java desktop"
  | "Android"
  | "Flutter"
  | "Microservices"
  | "Microfrontends"
  | "Security"
  | "GCP";

export type ValidCategory =
  | "Full Stack"
  | "MERN Stack"
  | "Next js"
  | "Typescript"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "Intigration"
  | "REST API"
  | "3D Modeling"
  | "Desktop App";

export type ValidExpType = "Personal Project" | "Professional";

export type ValidPages =
  | "skills"
  | "experience"
  | "contact"
  | "contributions"
  | "educations"
  | "aboutme";
